### ISSUE TITLE
Add formatting and linting rules

### ISSUE THREAD

**Issue by AlejandroSuero** [ethanholz/freeze.nvim#8]
# Motivation

To enforce a code style and add better diagnostics in the editor.

## Formatting

To keep all the changes to the code base [stylua](https://github.com/JohnnyMorganz/StyLua) would be a nice addition in `stylua.toml` or `.stylua.toml` file.

<details>
<summary>stylua.toml example</summary>

```toml
column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
collapse_simple_statement = "Never"

[sort_requires]
enabled = true
```

</details>

It can be combined with [editorconfig](https://editorconfig.org/) now supported on NeoVim.

<details>
<summary>.editorconfig</summary>

```editorconfig
root = true

[*]
indent_style = space
indent_size = 2
charset = utf-8
end_of_file = "lf"
trim_trailing_whitespace = true
insert_final_newline = false

[*.yml]
indent_style = space
indent_size = 2

# This makes it a lot less painful to write YAMLs in docs
[*.md]
indent_style = space
indent_size = 2
```

</details>

## Linting

For linting lua files there is to main options [luacheck](https://github.com/mpeterv/luacheck) and [selene](https://github.com/Kampfkarren/selene). My personal opinion is that **selene** is better in the way that is currently being maintained unlike **luacheck** and throws errors in a more readable way. Also the configuration for **selene** is easier, **luacheck** uses *codes* for the linting rules (ignore { "212" }), **selene** on the other hand, uses *named rules* (undefined_variable="allow").

<details>
<summary>selene example</summary>

```toml
# selene.toml
std="neovim" # read from `neovim.yml`

exclude = ["./*.rockspec"]

[rules]
global_usage = "warn"
multiple_statements = "allow"
incorrect_standard_library_use = "allow"
mixed_table = "allow"
unused_variable = "warn"
```

```yaml
# neovim.yml
---
base: lua51

globals:
  jit:
    any: true
  vim:
    any: true
  assert:
    args:
      - type: bool
      - type: string
        required: false
  after_each:
    args:
      - type: function
  before_each:
    args:
      - type: function
  describe:
    args:
      - type: string
      - type: function
  it:
    args:
      - type: string
      - type: function
```

> Documentation for selene [here](https://kampfkarren.github.io/selene/)

</details>

<details>
<summary>luacheck example</summary>

```lua
-- Example pulled from `plenary.nvim` repo
-- Rerun tests only if their modification time changed.
cache = true

std = luajit
codes = true

self = false

-- Glorious list of warnings: https://luacheck.readthedocs.io/en/stable/warnings.html
ignore = {
  "212", -- Unused argument, In the case of callback function, _arg_name is easier to understand than _, so this option is set to off.
  "122", -- Indirectly setting a readonly global
}

globals = {
  "_",
  "_PlenaryLeafTable",
  "_PlenaryBustedOldAssert",
  "_AssociatedBufs",
}

-- Global objects defined by the C code
read_globals = {
  "vim",
}

exclude_files = {
  "lua/plenary/profile/lua_profiler.lua",
  "lua/plenary/profile/memory_profiler.lua",
  "lua/plenary/async_lib/*.lua",
}

files = {
  ["lua/plenary/busted.lua"] = {
    globals = {
      "describe",
      "it",
      "pending",
      "before_each",
      "after_each",
      "clear",
      "assert",
      "print",
    },
  },
  ["lua/plenary/async/init.lua"] = {
    globals = {
      "a",
    },
  },
  ["lua/plenary/async/tests.lua"] = {
    globals = {
      "describe",
      "it",
      "pending",
      "before_each",
      "after_each",
    },
  },
}
```

> Documentation for luacheck [here](https://luacheck.readthedocs.io/en/stable/)

</details>

### Adding it to CI

If we want to add it to [GitHub workflows](https://docs.github.com/en/actions/using-workflows) it will be simple.

<details>
<summary>Selene action example</summary>

```yaml
name: lint

on: ["push", "pull_request"]

jobs:
  lint:
    name: Selene check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Run selene
        uses: NTBBloodbath/selene-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --display-style quiet lua/freeze

  style-lint:
    name: Stylua check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Lint with stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --color always --check lua/freeze
```

</details>

<details>
<summary>Luacheck example</summary>

```yaml
name: lint

on: ["push", "pull_request"]

jobs:
  lint:
    name: Luacheck check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install luacheck

      - name: Lint
        run: luacheck lua/freeze

  style-lint:
    name: Stylua check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Lint with stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check lua/freeze
```

</details>
